theme: jekyll-theme-cayman
title: Interval Prediction for Continuous-Time Systems with Parametric Uncertainties
description: Edouard Leurent, Denis Efimov, Tarek Raïssi, Wilfrid Perruquetti

github:
  repository_url: https://github.com/eleurent/rl-agents#irp-interval-based-robust-planning
  paper_url: https://arxiv.org/abs/1904.04727